// <auto-generated />
using System;
using ContactsBook.DataAccess.MsSql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactsBook.DataAccess.MsSql.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    [Migration("20210521232715_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactsBook.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(28)
                        .HasColumnType("nvarchar(28)");

                    b.Property<long>("PhoneNumber")
                        .HasMaxLength(11)
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33d5c018-e207-4931-ad11-cc99aca70fa5"),
                            Email = "Holly.Pacocha@gmail.com",
                            Name = "Holly Pacocha",
                            PhoneNumber = 67468880795L
                        },
                        new
                        {
                            Id = new Guid("5b6d8694-fe3e-4c72-a477-c2c46a0db984"),
                            Email = "Terry.Blick@gmail.com",
                            Name = "Terry Blick",
                            PhoneNumber = 80114973233L
                        },
                        new
                        {
                            Id = new Guid("38eb3d9f-4363-447c-9ee4-8d826663f609"),
                            Email = "Teresa.Von@yahoo.com",
                            Name = "Teresa Von",
                            PhoneNumber = 72719569938L
                        },
                        new
                        {
                            Id = new Guid("5fac7bc8-e75e-48e4-b7b6-e3db84811b13"),
                            Email = "Lynda38@hotmail.com",
                            Name = "Lynda Conn",
                            PhoneNumber = 38164042499L
                        },
                        new
                        {
                            Id = new Guid("64eff27e-a1fd-4c81-9b8e-3284015e4d51"),
                            Email = "Matthew_Turcotte19@hotmail.com",
                            Name = "Matthew Turcotte",
                            PhoneNumber = 73041681699L
                        },
                        new
                        {
                            Id = new Guid("6a4e2564-1cc4-42e5-9943-d69f6243d080"),
                            Email = "Jason.West@gmail.com",
                            Name = "Jason West",
                            PhoneNumber = 69258162313L
                        },
                        new
                        {
                            Id = new Guid("73438832-4e7b-4ccf-8ca8-2a5b5545a8ce"),
                            Email = "Alexandra_Heaney@hotmail.com",
                            Name = "Alexandra Heaney",
                            PhoneNumber = 41036540037L
                        },
                        new
                        {
                            Id = new Guid("727cca1f-5e4c-46f2-a873-0303a734233d"),
                            Email = "Daisy.Price47@hotmail.com",
                            Name = "Daisy Price",
                            PhoneNumber = 42836871502L
                        },
                        new
                        {
                            Id = new Guid("4044eb06-5d6b-4a91-b139-e1baec13973c"),
                            Email = "Gail52@hotmail.com",
                            Name = "Gail Dach",
                            PhoneNumber = 16016746352L
                        },
                        new
                        {
                            Id = new Guid("f3a577a5-c9ea-43fe-ad40-270692fb5bdb"),
                            Email = "Derek.Donnelly@yahoo.com",
                            Name = "Derek Donnelly",
                            PhoneNumber = 44342389262L
                        },
                        new
                        {
                            Id = new Guid("941349ce-e9f2-4d09-936c-32d0768c7212"),
                            Email = "Edith_Jacobi@yahoo.com",
                            Name = "Edith Jacobi",
                            PhoneNumber = 93203980481L
                        },
                        new
                        {
                            Id = new Guid("9e55ce38-8297-4052-bfef-2080cbe9d20a"),
                            Email = "Cristina34@yahoo.com",
                            Name = "Cristina Smitham",
                            PhoneNumber = 13749512664L
                        },
                        new
                        {
                            Id = new Guid("820b415b-85c6-4f3d-b88c-c8ec77cdbd95"),
                            Email = "Timmy_Okuneva@hotmail.com",
                            Name = "Timmy Okuneva",
                            PhoneNumber = 83102825876L
                        },
                        new
                        {
                            Id = new Guid("41d4947a-7856-4553-afcf-e3ad705aba3b"),
                            Email = "Sherry_Wolf@gmail.com",
                            Name = "Sherry Wolf",
                            PhoneNumber = 43577179044L
                        },
                        new
                        {
                            Id = new Guid("b34875a1-8796-44d8-9f89-7f9cbb9bbbab"),
                            Email = "Wilbert_Goyette16@gmail.com",
                            Name = "Wilbert Goyette",
                            PhoneNumber = 64393753681L
                        },
                        new
                        {
                            Id = new Guid("5b54f2e4-7029-45fb-a8ef-2cc85bca95c0"),
                            Email = "Earl_Kshlerin20@yahoo.com",
                            Name = "Earl Kshlerin",
                            PhoneNumber = 48699023541L
                        },
                        new
                        {
                            Id = new Guid("60181006-47ee-49db-9f3f-0b175a0b15ff"),
                            Email = "Yvonne.Boyer13@hotmail.com",
                            Name = "Yvonne Boyer",
                            PhoneNumber = 77808273857L
                        },
                        new
                        {
                            Id = new Guid("6adab844-a831-44e7-b6c5-34c7912d5f4a"),
                            Email = "Vernon_Kiehn@gmail.com",
                            Name = "Vernon Kiehn",
                            PhoneNumber = 72223751573L
                        },
                        new
                        {
                            Id = new Guid("5af13175-1df1-48a0-9707-ddff84560de5"),
                            Email = "Rufus_Bergstrom@gmail.com",
                            Name = "Rufus Bergstrom",
                            PhoneNumber = 96977695639L
                        },
                        new
                        {
                            Id = new Guid("037c856b-6d15-4da7-95cf-4eea677ad97c"),
                            Email = "Timmy.King@gmail.com",
                            Name = "Timmy King",
                            PhoneNumber = 77631584637L
                        },
                        new
                        {
                            Id = new Guid("48ce22ed-cce6-4239-8a29-643e32b28f78"),
                            Email = "Shannon80@yahoo.com",
                            Name = "Shannon Batz",
                            PhoneNumber = 82328311620L
                        },
                        new
                        {
                            Id = new Guid("d92d0388-a988-431c-a8f3-595e9b994be5"),
                            Email = "Pamela.Cremin61@yahoo.com",
                            Name = "Pamela Cremin",
                            PhoneNumber = 65544495612L
                        },
                        new
                        {
                            Id = new Guid("3cb774b7-5c35-429b-a018-726af0fd9a37"),
                            Email = "Rickey.Bechtelar@yahoo.com",
                            Name = "Rickey Bechtelar",
                            PhoneNumber = 95804890945L
                        },
                        new
                        {
                            Id = new Guid("adf3c74a-9b84-4ecb-9779-732c3614c759"),
                            Email = "Renee_Halvorson68@hotmail.com",
                            Name = "Renee Halvorson",
                            PhoneNumber = 47185066378L
                        },
                        new
                        {
                            Id = new Guid("266416b7-1722-40ab-8714-55803e8c94bb"),
                            Email = "Allan.Nader48@hotmail.com",
                            Name = "Allan Nader",
                            PhoneNumber = 47906644934L
                        },
                        new
                        {
                            Id = new Guid("494984f4-7d87-4ad5-8b44-b0aec2d9ba8f"),
                            Email = "Kathleen.Kuhic68@gmail.com",
                            Name = "Kathleen Kuhic",
                            PhoneNumber = 61818545359L
                        },
                        new
                        {
                            Id = new Guid("d6cfc31f-a2b9-4dbb-aede-32aa1283e7ab"),
                            Email = "Ben_Bergstrom@hotmail.com",
                            Name = "Ben Bergstrom",
                            PhoneNumber = 19370890930L
                        },
                        new
                        {
                            Id = new Guid("15bcab84-921e-49e6-ac8b-4efb9504bf7d"),
                            Email = "Earl.Osinski@yahoo.com",
                            Name = "Earl Osinski",
                            PhoneNumber = 62095650700L
                        },
                        new
                        {
                            Id = new Guid("114cb444-d027-4851-84b2-ab95a6f0a78d"),
                            Email = "Norman87@yahoo.com",
                            Name = "Norman Schuppe",
                            PhoneNumber = 55571766894L
                        },
                        new
                        {
                            Id = new Guid("274318ab-7067-4d3a-823d-9a532c7cede9"),
                            Email = "Annie14@yahoo.com",
                            Name = "Annie Wolf",
                            PhoneNumber = 37608332963L
                        },
                        new
                        {
                            Id = new Guid("51456fd6-e435-4209-a26f-0f1cb099455b"),
                            Email = "Brandy.Funk@yahoo.com",
                            Name = "Brandy Funk",
                            PhoneNumber = 97739787118L
                        },
                        new
                        {
                            Id = new Guid("3755a4cb-55aa-40f4-bb74-41fc6808a118"),
                            Email = "Yolanda_Kozey@hotmail.com",
                            Name = "Yolanda Kozey",
                            PhoneNumber = 96359637442L
                        },
                        new
                        {
                            Id = new Guid("b48dd95e-219e-439c-a544-0980af173f81"),
                            Email = "Estelle.Reinger@yahoo.com",
                            Name = "Estelle Reinger",
                            PhoneNumber = 95611155784L
                        },
                        new
                        {
                            Id = new Guid("62ac6dd7-2140-40ed-bb1c-de456b56009b"),
                            Email = "Thomas94@gmail.com",
                            Name = "Thomas Trantow",
                            PhoneNumber = 26717778638L
                        },
                        new
                        {
                            Id = new Guid("04eb1547-7850-4e43-85f5-1c2fd146e47b"),
                            Email = "Martha_Runolfsson66@hotmail.com",
                            Name = "Martha Runolfsson",
                            PhoneNumber = 62671828005L
                        },
                        new
                        {
                            Id = new Guid("84caa8b7-9f26-46fc-b7eb-63a6fa7f0d71"),
                            Email = "Alexandra.Littel1@gmail.com",
                            Name = "Alexandra Littel",
                            PhoneNumber = 84000275034L
                        },
                        new
                        {
                            Id = new Guid("4e2b9c0d-4399-425f-98a0-06bab9e1b374"),
                            Email = "Crystal27@gmail.com",
                            Name = "Crystal Heller",
                            PhoneNumber = 90213429536L
                        },
                        new
                        {
                            Id = new Guid("c8d1bae9-fc94-4d83-a8d2-4cf154e1ff19"),
                            Email = "Nathaniel_Gerhold57@hotmail.com",
                            Name = "Nathaniel Gerhold",
                            PhoneNumber = 44333592497L
                        },
                        new
                        {
                            Id = new Guid("c42d2a78-a03f-41e7-957c-2cf0b4bbb925"),
                            Email = "Marshall84@gmail.com",
                            Name = "Marshall O'Hara",
                            PhoneNumber = 11785620135L
                        },
                        new
                        {
                            Id = new Guid("2fdecbb8-9b4a-4c6f-bfd9-8b75e30be633"),
                            Email = "Vivian_Armstrong3@yahoo.com",
                            Name = "Vivian Armstrong",
                            PhoneNumber = 47241681230L
                        },
                        new
                        {
                            Id = new Guid("bcb749d1-3e20-4b28-bd03-373794e76b10"),
                            Email = "Alice99@yahoo.com",
                            Name = "Alice Vandervort",
                            PhoneNumber = 99465892514L
                        },
                        new
                        {
                            Id = new Guid("3419563d-1ef1-4650-9256-6a351b7512c4"),
                            Email = "Curtis53@hotmail.com",
                            Name = "Curtis Buckridge",
                            PhoneNumber = 65291823728L
                        },
                        new
                        {
                            Id = new Guid("d26bbd2b-7103-4cbb-ae6a-43f0c8db2d10"),
                            Email = "Margaret_Schulist57@gmail.com",
                            Name = "Margaret Schulist",
                            PhoneNumber = 42393857786L
                        },
                        new
                        {
                            Id = new Guid("bfad2469-52b4-4048-81f4-cb4ad9737b6b"),
                            Email = "Pearl.Roberts@hotmail.com",
                            Name = "Pearl Roberts",
                            PhoneNumber = 24003938541L
                        },
                        new
                        {
                            Id = new Guid("f2881559-b940-43aa-b0c9-d487babe1c1b"),
                            Email = "Joanna54@gmail.com",
                            Name = "Joanna Block",
                            PhoneNumber = 90476852049L
                        },
                        new
                        {
                            Id = new Guid("1a1d1531-ee95-429b-9c7d-2ed9cdf3b9b3"),
                            Email = "Doris53@yahoo.com",
                            Name = "Doris Auer",
                            PhoneNumber = 76244148866L
                        },
                        new
                        {
                            Id = new Guid("532b75ac-838e-4ce8-a909-fea867b55dbe"),
                            Email = "Clarence55@yahoo.com",
                            Name = "Clarence Thompson",
                            PhoneNumber = 94743814255L
                        },
                        new
                        {
                            Id = new Guid("c0fe8c8d-9dc7-4ad4-9298-dcd152b007f4"),
                            Email = "June4@gmail.com",
                            Name = "June Wiza",
                            PhoneNumber = 32715616046L
                        },
                        new
                        {
                            Id = new Guid("9f654aec-1bf5-4fff-bb61-9537cabfb82a"),
                            Email = "Andrew76@hotmail.com",
                            Name = "Andrew Greenholt",
                            PhoneNumber = 63906534395L
                        },
                        new
                        {
                            Id = new Guid("00aaed29-5f0f-41e0-a25d-b204c534f6e5"),
                            Email = "Duane.Prosacco35@hotmail.com",
                            Name = "Duane Prosacco",
                            PhoneNumber = 65939801254L
                        },
                        new
                        {
                            Id = new Guid("fde99049-021f-4331-a7df-6b80be67153c"),
                            Email = "Angel52@yahoo.com",
                            Name = "Angel O'Conner",
                            PhoneNumber = 18533744117L
                        },
                        new
                        {
                            Id = new Guid("b4a9dc25-a553-4f05-9206-3f6fa0f3097b"),
                            Email = "Seth.Ledner21@yahoo.com",
                            Name = "Seth Ledner",
                            PhoneNumber = 61587560056L
                        },
                        new
                        {
                            Id = new Guid("38def77d-e71d-42ee-a964-0695103a1531"),
                            Email = "Fannie.Littel75@yahoo.com",
                            Name = "Fannie Littel",
                            PhoneNumber = 95142309504L
                        },
                        new
                        {
                            Id = new Guid("32142c8f-9b0d-4767-a8a0-a6579975c1d6"),
                            Email = "Frederick_McClure@hotmail.com",
                            Name = "Frederick McClure",
                            PhoneNumber = 21661263742L
                        },
                        new
                        {
                            Id = new Guid("65b5627b-c8db-4667-9ca6-50912d2c43e3"),
                            Email = "Rick13@gmail.com",
                            Name = "Rick Gislason",
                            PhoneNumber = 50231272950L
                        },
                        new
                        {
                            Id = new Guid("3535102e-2283-4c99-9547-9309f826387d"),
                            Email = "Regina.Schamberger0@gmail.com",
                            Name = "Regina Schamberger",
                            PhoneNumber = 79093908564L
                        },
                        new
                        {
                            Id = new Guid("8ccf4a6d-a32b-4595-aabd-666b955883cd"),
                            Email = "Russell.Abernathy92@gmail.com",
                            Name = "Russell Abernathy",
                            PhoneNumber = 41040186584L
                        },
                        new
                        {
                            Id = new Guid("1d041d82-d38a-4da1-875c-bfa037f952f8"),
                            Email = "Derrick_Hettinger28@yahoo.com",
                            Name = "Derrick Hettinger",
                            PhoneNumber = 96072341466L
                        },
                        new
                        {
                            Id = new Guid("abe3b179-f548-4aaa-8e6b-5ad0076c64b3"),
                            Email = "Darrel_Yundt42@gmail.com",
                            Name = "Darrel Yundt",
                            PhoneNumber = 20749904984L
                        },
                        new
                        {
                            Id = new Guid("c77938b1-2795-4257-a7dc-f0b7aac7568e"),
                            Email = "Tara27@hotmail.com",
                            Name = "Tara Blick",
                            PhoneNumber = 28060260419L
                        },
                        new
                        {
                            Id = new Guid("e8978be1-0a5a-45e7-a3bb-c06c1864e894"),
                            Email = "Crystal42@hotmail.com",
                            Name = "Crystal Kertzmann",
                            PhoneNumber = 69405921645L
                        },
                        new
                        {
                            Id = new Guid("6c94de67-89d9-42a6-b21c-6eb284ecdc09"),
                            Email = "Jimmie.Gusikowski@hotmail.com",
                            Name = "Jimmie Gusikowski",
                            PhoneNumber = 21648677602L
                        },
                        new
                        {
                            Id = new Guid("838ec341-6447-4cad-b91c-7f05c17aa2b3"),
                            Email = "Daisy_Streich@yahoo.com",
                            Name = "Daisy Streich",
                            PhoneNumber = 12896673881L
                        },
                        new
                        {
                            Id = new Guid("d03c4648-0014-4acb-9fe0-2cfc6cd22796"),
                            Email = "Nick96@yahoo.com",
                            Name = "Nick Oberbrunner",
                            PhoneNumber = 93792188709L
                        },
                        new
                        {
                            Id = new Guid("65fd7234-7d16-4f5e-9303-1318d37c0126"),
                            Email = "Edna34@yahoo.com",
                            Name = "Edna Bartoletti",
                            PhoneNumber = 38011369234L
                        },
                        new
                        {
                            Id = new Guid("83330f91-ce15-4eba-93e8-203a7ce664a7"),
                            Email = "Bernard.Torphy14@yahoo.com",
                            Name = "Bernard Torphy",
                            PhoneNumber = 35292836989L
                        },
                        new
                        {
                            Id = new Guid("b51edd27-9260-4c9f-9225-fb0d885f50a2"),
                            Email = "Eleanor4@gmail.com",
                            Name = "Eleanor Ward",
                            PhoneNumber = 32085267842L
                        },
                        new
                        {
                            Id = new Guid("98b67a48-4dae-4e9c-b87f-a0b014862ecb"),
                            Email = "Marvin3@yahoo.com",
                            Name = "Marvin Deckow",
                            PhoneNumber = 41556913313L
                        },
                        new
                        {
                            Id = new Guid("3527485b-f2ad-4c4d-b8a4-c18e69a7b238"),
                            Email = "Bernadette18@gmail.com",
                            Name = "Bernadette Stark",
                            PhoneNumber = 94415393603L
                        },
                        new
                        {
                            Id = new Guid("80a33566-acf0-43f9-b3a1-79c332792e68"),
                            Email = "Kim30@gmail.com",
                            Name = "Kim Dietrich",
                            PhoneNumber = 36281547051L
                        },
                        new
                        {
                            Id = new Guid("1d6ee606-ae08-4e8a-beaf-3454cb451d2e"),
                            Email = "Amy_Veum51@yahoo.com",
                            Name = "Amy Veum",
                            PhoneNumber = 75027030014L
                        },
                        new
                        {
                            Id = new Guid("0e40fd64-f47f-482d-99b6-f67046dd05e7"),
                            Email = "Edna64@yahoo.com",
                            Name = "Edna Blick",
                            PhoneNumber = 46707694193L
                        },
                        new
                        {
                            Id = new Guid("efc6a94b-ea4b-42be-af29-28aaed83b745"),
                            Email = "Roberta.Green@yahoo.com",
                            Name = "Roberta Green",
                            PhoneNumber = 46875330497L
                        },
                        new
                        {
                            Id = new Guid("86d30396-0c7c-43fd-9af2-2490481a213a"),
                            Email = "Brad.Heller26@gmail.com",
                            Name = "Brad Heller",
                            PhoneNumber = 10471027545L
                        },
                        new
                        {
                            Id = new Guid("344a7f87-cf1a-4ccc-bba4-f3ba67065d44"),
                            Email = "Bruce_Zulauf92@gmail.com",
                            Name = "Bruce Zulauf",
                            PhoneNumber = 69702255115L
                        },
                        new
                        {
                            Id = new Guid("e88a3118-e962-4916-9e5c-731174e539d0"),
                            Email = "Alfred.Barton29@gmail.com",
                            Name = "Alfred Barton",
                            PhoneNumber = 85680523582L
                        },
                        new
                        {
                            Id = new Guid("527831a0-ce2e-4238-ae8a-91bbe38346f0"),
                            Email = "Arthur_Franecki@yahoo.com",
                            Name = "Arthur Franecki",
                            PhoneNumber = 70614671460L
                        },
                        new
                        {
                            Id = new Guid("808884b1-816c-43f3-bc3b-de89c6622ba0"),
                            Email = "Spencer66@yahoo.com",
                            Name = "Spencer Daugherty",
                            PhoneNumber = 32715586541L
                        },
                        new
                        {
                            Id = new Guid("c2e7496a-dddb-4b7f-a4b1-04e5985d9147"),
                            Email = "Sherman.Rice@yahoo.com",
                            Name = "Sherman Rice",
                            PhoneNumber = 64373445293L
                        },
                        new
                        {
                            Id = new Guid("8d540623-de22-4749-b0d2-b4d3eb18e743"),
                            Email = "Patty.Satterfield83@gmail.com",
                            Name = "Patty Satterfield",
                            PhoneNumber = 45188450103L
                        },
                        new
                        {
                            Id = new Guid("0ac22cd4-e36f-42b9-b030-423cb5e61186"),
                            Email = "Sherry_Metz69@yahoo.com",
                            Name = "Sherry Metz",
                            PhoneNumber = 38345682238L
                        },
                        new
                        {
                            Id = new Guid("b0f06db5-ca26-4234-b354-68b376f1c02e"),
                            Email = "Paulette91@gmail.com",
                            Name = "Paulette Balistreri",
                            PhoneNumber = 17082520680L
                        },
                        new
                        {
                            Id = new Guid("96dee879-9a38-40e7-bb62-7bfb10ceacf5"),
                            Email = "Hazel.Schimmel@gmail.com",
                            Name = "Hazel Schimmel",
                            PhoneNumber = 33697748200L
                        },
                        new
                        {
                            Id = new Guid("d03cf164-c12d-42f8-9b8c-6f1c1b2d9fe7"),
                            Email = "Dan_Lowe51@yahoo.com",
                            Name = "Dan Lowe",
                            PhoneNumber = 33640494101L
                        },
                        new
                        {
                            Id = new Guid("f93bfb2b-5151-47b4-a307-9bbabbfab7ad"),
                            Email = "Sammy.Jaskolski@gmail.com",
                            Name = "Sammy Jaskolski",
                            PhoneNumber = 45712344490L
                        },
                        new
                        {
                            Id = new Guid("b2df4f8c-ac10-40cb-a28a-de46d9d746d1"),
                            Email = "Rodney.Hoeger58@hotmail.com",
                            Name = "Rodney Hoeger",
                            PhoneNumber = 37581367207L
                        },
                        new
                        {
                            Id = new Guid("8517f29a-ff6f-42a0-be03-3f600eb7ad70"),
                            Email = "Maryann_Gerlach@gmail.com",
                            Name = "Maryann Gerlach",
                            PhoneNumber = 57392741310L
                        },
                        new
                        {
                            Id = new Guid("b11195de-7785-4f76-9afd-066687a1716d"),
                            Email = "Ida_Wiegand@yahoo.com",
                            Name = "Ida Wiegand",
                            PhoneNumber = 72718047156L
                        },
                        new
                        {
                            Id = new Guid("77ab99ce-7c15-4c66-8d80-b2f06c2a6bda"),
                            Email = "Darlene_Lockman@yahoo.com",
                            Name = "Darlene Lockman",
                            PhoneNumber = 28766894084L
                        },
                        new
                        {
                            Id = new Guid("fec27d9a-0669-40e4-8cc0-de2ff5a38d3e"),
                            Email = "Amelia68@gmail.com",
                            Name = "Amelia Armstrong",
                            PhoneNumber = 94815621349L
                        },
                        new
                        {
                            Id = new Guid("69897d1f-8d7d-460a-8aea-1e5178c8d976"),
                            Email = "Yvette_Lubowitz@yahoo.com",
                            Name = "Yvette Lubowitz",
                            PhoneNumber = 56899276458L
                        },
                        new
                        {
                            Id = new Guid("454e6139-95af-4fd9-b6e7-1484132e5928"),
                            Email = "Alfredo.Kling46@yahoo.com",
                            Name = "Alfredo Kling",
                            PhoneNumber = 56597214963L
                        },
                        new
                        {
                            Id = new Guid("1ee66d37-fe73-4a24-b212-037ff2be5f4c"),
                            Email = "Antoinette.OHara@hotmail.com",
                            Name = "Antoinette O'Hara",
                            PhoneNumber = 42893055106L
                        },
                        new
                        {
                            Id = new Guid("a9c0914b-5f25-4064-92b3-a9f015a3cefe"),
                            Email = "Lee43@gmail.com",
                            Name = "Lee Keeling",
                            PhoneNumber = 51107768104L
                        },
                        new
                        {
                            Id = new Guid("f063b46b-4d8a-47b4-8370-5118fcfee2f3"),
                            Email = "Cecelia_Larkin55@yahoo.com",
                            Name = "Cecelia Larkin",
                            PhoneNumber = 67935456041L
                        },
                        new
                        {
                            Id = new Guid("d5eafa70-da68-4c8e-91e5-974099792b78"),
                            Email = "Traci.Prohaska46@hotmail.com",
                            Name = "Traci Prohaska",
                            PhoneNumber = 46806904662L
                        },
                        new
                        {
                            Id = new Guid("804655d0-bd80-4e77-9458-c583e5483567"),
                            Email = "Julius_Connelly@hotmail.com",
                            Name = "Julius Connelly",
                            PhoneNumber = 61030624877L
                        },
                        new
                        {
                            Id = new Guid("c768eaf8-c4b9-4db3-be08-16ba11a6789b"),
                            Email = "Dana_Kuhn24@yahoo.com",
                            Name = "Dana Kuhn",
                            PhoneNumber = 28995719705L
                        },
                        new
                        {
                            Id = new Guid("6d832461-3252-4078-9c5f-c91e7617cc55"),
                            Email = "Valerie3@yahoo.com",
                            Name = "Valerie D'Amore",
                            PhoneNumber = 38757823058L
                        },
                        new
                        {
                            Id = new Guid("23f46120-7d04-4195-b805-cea968bb8d38"),
                            Email = "Alex5@hotmail.com",
                            Name = "Alex Bashirian",
                            PhoneNumber = 47846396233L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
